CREATE TABLE IF NOT EXISTS `acreditacion_historico` (
  `id` int(40) NOT NULL AUTO_INCREMENT,
  `acreditacion_id` int(40) NOT NULL,
  `fecha` date NOT NULL,
  `nombre` varchar(255) NOT NULL DEFAULT '',
  `nombreapellido` varchar(255) NOT NULL,
  `formacion` varchar(255) NOT NULL,
  `titulo` varchar(255) NOT NULL DEFAULT '',
  `documento` varchar(255) NOT NULL,
  `fechanacimiento` date NOT NULL,
  `direccionpostal` varchar(255) NOT NULL,
  `direccionelectronica` varchar(255) NOT NULL,
  `telefonocontacto` varchar(255) NOT NULL,
  `instituciondesempeno` int(11) NOT NULL,
  `laboratoriounidad` varchar(255) NOT NULL,
  `cargofuncioninstitucion` varchar(255) NOT NULL,
  `cargahorariasemanal` int(11) NOT NULL,
  `nombresupervisor` varchar(255) NOT NULL,
  `especiestrabajadas` text NOT NULL,
  `describatareas` text NOT NULL,
  `pctinvestigacion` int(11) NOT NULL,
  `pctmedicinaclinica` int(11) NOT NULL,
  `pctcirugia` int(11) NOT NULL,
  `pctmantenimientocolonias` int(11) NOT NULL,
  `pctmanipulacion` int(11) NOT NULL,
  `pctdirprojectos` int(11) NOT NULL,
  `pctnecropsia` int(11) NOT NULL,
  `pctdiaglaboratorio` int(11) NOT NULL,
  `pctceua` int(11) NOT NULL,
  `pcthistopatologia` int(11) NOT NULL,
  `pctentedu` int(11) NOT NULL,
  `pctapoyoinvestigadores` int(11) NOT NULL,
  `pctsupervision` int(11) NOT NULL,
  `pctprodanimal` int(11) NOT NULL,
  `pctlegal` int(11) NOT NULL,
  `pctotrasfunciones` int(11) NOT NULL,
  `pctfuncnorel` int(11) NOT NULL,
  `pctobservaciones` text NOT NULL,
  `realizocursos` tinyint(1) NOT NULL,
  `acrpersonales` tinyint(1) NOT NULL,
  `curso1` varchar(255) DEFAULT NULL,
  `curso2` varchar(255) DEFAULT NULL,
  `curso3` varchar(255) DEFAULT NULL,
  `cursoobservacion` text,
  `acrorganismo` varchar(255) DEFAULT NULL,
  `acrcategoria` varchar(255) DEFAULT NULL,
  `acrfecha` date DEFAULT NULL,
  `categoria` varchar(255) NOT NULL,
  `categoriaA` tinyint(1) NOT NULL DEFAULT '0',
  `categoriaB` tinyint(1) NOT NULL DEFAULT '0',
  `categoriaC1` tinyint(1) NOT NULL DEFAULT '0',
  `categoriaC2` tinyint(1) NOT NULL DEFAULT '0',
  `cvfile` varchar(255) NOT NULL,
  `cvpath` varchar(255) NOT NULL,
  `isactive` tinyint(1) NOT NULL,
  `estado` varchar(2) NOT NULL DEFAULT 'N',
  `fechavencimiento` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `acreditacion_historico` ADD `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;

CREATE TABLE IF NOT EXISTS `acreditacionarchivo_historico` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `acreditacion_historico_id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `filepath` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `acreditacion_historico_id` (`acreditacion_historico_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `acreditacionarchivo_historico` ADD `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;