<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
$lang['instituciones.bases.titulo']='Bases registro de instituciones';
$lang['instituciones.bases.contenido']='<h2>REGISTRO NACIONAL DE INSTITUCIONES QUE CR&iacute;EN, UTILICEN O TRANSPORTEN ANIMALES EN EXPERIMENTACI&oacute;N, DOCENCIA E INVESTIGACI&oacute;N CIENT&iacute;FICA</h2>
		<h4>Objetivo</h4>
		<p>La Comisi&oacute;n Nacional de Experimentaci&oacute;n Animal (CNEA) convoca a todas las <strong>Instituciones</strong> que cr&iacute;en, utilicen o transporten animales en experimentaci&oacute;n, docencia e investigaci&oacute;n cient&iacute;fica a formar parte de un <strong>Registro Nacional</strong>. Con dicho registro cada Instituci&oacute;n cumplir&aacute; con el <strong>Art&iacute;culo N&ordm; 8-inciso D</strong> de la <a href="http://sip.parlamento.gub.uy/leyes/AccesoTextoLey.asp?Ley=18611&Anchor=" target="_blank">Ley N&ordm; 18.611</a> en el que se establece que, entre los cometidos de la CNEA est&aacute; el de <strong>"Mantener un registro actualizado de las instituciones para cr&iacute;a, utilizaci&oacute;n o transporte de animales en experimentaci&oacute;n, docencia e investigaci&oacute;n cient&iacute;fica."</h4>
		<h4>&iquest;Qui&eacute;nes deben presentarse?</h4>
		<p>Deben registrarse todas aquellas Instituciones que cr&iacute;en, utilicen o transporten animales en experimentaci&oacute;n, docencia e investigaci&oacute;n cient&iacute;fica que se encuentren en el territorio nacional.</p>
		<h4>&iquest;Es obligatorio presentarse?</h4>
		<p>S&iacute;. Todas las personas que realicen experimentaci&oacute;n con animales en las <strong>Instituciones registradas</strong> as&iacute; como los procedimientos experimentales de las mismas, <strong>quedar&aacute;n habilitadas y amparadas por la</strong> <a href="http://sip.parlamento.gub.uy/leyes/AccesoTextoLey.asp?Ley=18611&Anchor=" target="_blank">Ley N&ordm; 18.611</a></p>
		<h4>Procedimiento de registro</h4>
		<p>Las solicitudes deber&aacute;n completarse a trav&eacute;s del formulario que est&aacute; disponible en el portal <a href="http://www.cnea.org.uy" target="_blank">www.cnea.org.uy</a> con toda la informaci&oacute;n que se solicita. Al finalizar, se deber&aacute; enviar el formulario completo, firmado (se aceptan firmas electr&oacute;nicas) y la resoluci&oacute;n institucional de la constituci&oacute;n del CEUA (ver &iacute;tem 4 de formulario) a la direcci&oacute;n de correo electr&oacute;nico: <a href="mailto:secretaria@cnea.org.uy">secretaria@cnea.org.uy</a></p>
		<h4>Resoluci&oacute;n</h4>
		<p>Una vez recibida y procesada la informaci&oacute;n, la CNEA le adjudicar&aacute; un n&uacute;mero de tr&aacute;mite a cada Instituci&oacute;n al cual har&aacute; referencia en futuras acciones. La CNEA resolver&aacute; en un plazo de 60 d&iacute;as del cierre de la convocatoria, el ingreso de las instituciones solicitantes al Registro Nacional y lo comunicar&aacute; al responsable de cada instituci&oacute;n respectiva. En el portal <a href="http://www.cnea.org.uy" target="_blank">www.cnea.org.uy</a> se publicar&aacute; un listado de las instituciones incluidas en el Registro Nacional que se actualizar&aacute; cada 6 meses. Las instituciones que se registren deber&aacute;n cumplir, oportunamente, con la reglamentaci&oacute;n que dicte el Poder Ejecutivo, si correspondiere, dentro del plazo previsto por el art. 24 de la ley.</p>
		<h4>Per&iacute;odo de registro</h4>
		<p>El tr&aacute;mite para ingresar al Registro Nacional de Instituciones se podr&aacute; realizar a partir del 1&ordm; de agosto de 2011. S&oacute;lo aquellas instituciones que realicen el tr&aacute;mite antes del 1&ordm; de noviembre de 2011 podr&aacute;n ser incluidas en el Registro Nacional durante el a&ntilde;o 2011.</p><br />
		<p>Por Consultas: <a href="mailto:secretaria@cnea.org.uy">secretaria@cnea.org.uy</a></p>';
/* End of file instituciones_lang.php */